In [1]:
3 + 4

7

3 + 4

This is a **markdown** cell

# H1

## H2

### H3

In [2]:
!ls

Data_Analysis.ipynb countries.csv       image.jpg


![animal](image.jpg)

In [3]:
name = "Laura"
name

'Laura'

In [4]:
name = "Peter"
name

'Peter'

In [5]:
name 

'Peter'

# NumPy

In [44]:
import numpy as np # canonical import
import pandas as pd # canonical import

In [6]:
list_ = [[1, 2, 3], [4, 5, 6]]
print(type(list_))

list_ # list of lists

<class 'list'>


[[1, 2, 3], [4, 5, 6]]

In [10]:
array = np.array(list_)

print(type(array))

array # ndarray

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array.ndim

2

In [12]:
array.shape

(2, 3)

In [13]:
array.size

6

In [14]:
array.dtype

dtype('int64')

## Data Selection

In [15]:
# Let's build a 2D-array from a list of lists
data_list = [
    [ 0,  1,  2,  3,  4],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44],
]

data_np = np.array(data_list)
data_np

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

### Python way (horizontally) 

In [17]:
data_list[2][1:4]

[21, 22, 23]

### NumPy way (horizontally) 

In [19]:
data_np[2, 1:4]

array([21, 22, 23])

### Python way (vertically) 

In [20]:
# Pure Python
selection = []

for index, row in enumerate(data_list):
    if index > 0:
        selection.append(row[4])

selection # we could also have used list comprehension for fewer lines

[14, 24, 34, 44]

### NumPy way (verticallly) 

In [21]:
data_np[1:, 4]

array([14, 24, 34, 44])

In [26]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
array[1:7:2]

array([1, 3, 5])

## Vectorized Operations ⚡️

In [29]:
my_list = [
    [6, 5],
    [1, 3],
    [5, 6],
    [1, 4],
    [3, 7],
    [5, 8],
    [3, 5],
    [8, 4],
]

my_array = np.array(my_list)
my_array.ndim

2

### Python way

In [30]:
# Python way
sums = []

for row in my_list:
    sums.append(row[0] + row[1]) # standard integer "+" operator

sums

[11, 4, 11, 5, 10, 13, 8, 12]

### NumPy way

In [33]:
my_array[:, 0] + my_array[:, 1]

array([11,  4, 11,  5, 10, 13,  8, 12])

In [34]:
np.sum(my_array, axis=1)

array([11,  4, 11,  5, 10, 13,  8, 12])

In [35]:
np.sum(my_array, axis=0)

array([32, 42])

## How much faster is NumPy? ⚡️

In [36]:
# 2D-array of shape (10.000, 10.000) with random floats in the interval [0, 1]. That's 100M numbers!
array = np.random.rand(10000, 10000)
array_list = array.tolist()

In [37]:
%%time
total = 0

for row in array_list:
    for number in row:
        total += number

round(total, 2)

CPU times: user 9.29 s, sys: 3.79 s, total: 13.1 s
Wall time: 13.7 s


49996360.88

In [38]:
%%time
round(np.sum(array), 2)

CPU times: user 235 ms, sys: 847 ms, total: 1.08 s
Wall time: 2.05 s


49996360.88

## Boolean Indexing

In [42]:
my_list = [
    [6, 5],
    [1, 3],
    [5, 6],
    [1, 4],
    [3, 7],
    [5, 8],
    [3, 5],
    [8, 4],
]

my_array = np.array(my_list)

#mask = my_array > 5
my_array[my_array > 5]

array([6, 6, 7, 8, 8])

In [43]:
my_array[my_array > 5] = 0
my_array

array([[0, 5],
       [1, 3],
       [5, 0],
       [1, 4],
       [3, 0],
       [5, 0],
       [3, 5],
       [0, 4]])

# Introduction to Pandas

## Pandas Series

In [45]:
series = pd.Series(data=[1, 2, 'three'], index=['id1', 'id2', 'id3'])
series = pd.Series({'id1': 1, 'id2': 2, 'id3': 'three'})

series

id1        1
id2        2
id3    three
dtype: object

## Pandas Data Frame

In [47]:
df = pd.DataFrame(
    [[4, 7, 10],
    [5, 8, 11],
    [6, 9, 12]],
    index=['row_1', 'row_2', 'row_3'],
    columns=['col_a', 'col_b', 'col_c']
)

df

col_a  col_b  col_c
row_3      4      7     10
row_2      5      8     11
row_1      6      9     12

In [ ]:
apples  = pd.Series(data=[1, 2, 3], index=['id1', 'id2', 'id3'])
oranges = pd.Series(data=[4, 5, 6], index=['id1', 'id2', 'id3'])

dict_ = {
    'apples': apples,
    'oranges': oranges,
}

pd.DataFrame(dict_)